### ISSUE TITLE
Controllers showing up inconsistently/as Xbox controllers

### ISSUE THREAD

**Issue by caseyls** [CKProductionsDev/PlayStatus-Issues#1]
Hi! Let me begin with some info about my setup.

I have steam set to launch at windows startup directly into big picture mode. I set PlayStatus to launch at startup as well. I exclusively use controllers with steam, as my PC is plugged into my TV. I use a DualSense controller, and my partner uses a DualShock 4 controller.

The first issue is that when PlayStatus starts after steam starts, PlayStatus grabs windows focus and I can no longer use my controller to navigate big picture mode, until I get my keyboard and click on steam again. Would be amazing if this started up fully silently so it didn't interrupt the current window focus.

Second, it seems to detect both the dualsense and dualshock as Xbox controllers with the battery always at 100%. I've disabled steam input, and set PlayStation controller support to "only games without support," and set steam input to "default settings" for PlayStatus, but they still show up as Xbox controllers. 

I've gotten it to work inconsistently, i.e. at some point I had it showing both controllers as the actual controller type and their battery status correctly, but it's back to showing Xbox controllers again after a restart and I'm not sure why.

Would love any assistance! Thanks!

**Comment by c0redump3d** [comment]
Sorry! You'll want to set the following options:

1.) Under Steam -> Settings -> Controller set everything related to controllers to OFF (including PlayStation Controller Support to "Disabled.")

2.) Under Steam Library -> PlayStatus, right-click -> Properties -> Controller. Make sure to set the option to "Use Default Settings"

3.) For games that require Steam Input, you'll want to go to the game in your library -> Properties -> Controller and set to "Enabled"

This should fix your issues related to the controllers being detected as Xbox controllers. I had updated the instructions in app but had not updated them on this repo just yet.

As for the issue of PlayStatus taking focus when starting up, i'll definitely take a look later this week (since i'm not home currently :p). Let me know if this at least solves the issues related to your controllers!
